# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import DataB, Tr


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setMinimumSize(QtCore.QSize(600, 240))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.automatic_logon_checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.automatic_logon_checkBox.setObjectName("automatic_logon_checkBox")
        self.gridLayout_6.addWidget(self.automatic_logon_checkBox, 5, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(28, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 1, 7, 7, 1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 4, 4, 1, 1)
        self.forgot_psw_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.forgot_psw_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_psw_pushButton.setStyleSheet("#forgot_psw_pushButton{\n"
"    border:none;\n"
"}")
        self.forgot_psw_pushButton.setObjectName("forgot_psw_pushButton")
        self.gridLayout_6.addWidget(self.forgot_psw_pushButton, 5, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 4, 1, 1)
        self.LoginpushButton = QtWidgets.QPushButton(self.widget_2)
        self.LoginpushButton.setMinimumSize(QtCore.QSize(230, 40))
        self.LoginpushButton.setStyleSheet("#LoginpushButton{\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0, 170, 255);\n"
"    border-radius:7px;\n"
"}\n"
"#LoginpushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#LoginpushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoginpushButton.setIcon(icon)
        self.LoginpushButton.setObjectName("LoginpushButton")
        self.gridLayout_6.addWidget(self.LoginpushButton, 7, 2, 1, 4)
        self.remember_psw_checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.remember_psw_checkBox.setObjectName("remember_psw_checkBox")
        self.gridLayout_6.addWidget(self.remember_psw_checkBox, 5, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_3.setStyleSheet("border-image: url(:/icons/icons/密码.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 2, 6, 5, 1)
        self.Login_Account_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.Login_Account_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.Login_Account_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.Login_Account_lineEdit.setObjectName("Login_Account_lineEdit")
        self.gridLayout_6.addWidget(self.Login_Account_lineEdit, 1, 3, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(17, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 6, 4, 1, 1)
        self.logon_account_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.logon_account_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logon_account_pushButton.setStyleSheet("#logon_account_pushButton{\n"
"    border:none;\n"
"}")
        self.logon_account_pushButton.setObjectName("logon_account_pushButton")
        self.gridLayout_6.addWidget(self.logon_account_pushButton, 8, 0, 1, 1)
        self.Login_Account_lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.Login_Account_lineEdit_2.setMinimumSize(QtCore.QSize(200, 30))
        self.Login_Account_lineEdit_2.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.Login_Account_lineEdit_2.setText("")
        self.Login_Account_lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Login_Account_lineEdit_2.setObjectName("Login_Account_lineEdit_2")
        self.gridLayout_6.addWidget(self.Login_Account_lineEdit_2, 3, 3, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 1, 0, 7, 1)
        spacerItem6 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 2, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setStyleSheet("border:none;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/二维码.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 8, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setStyleSheet("border-image: url(:/icons/icons/用户.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 0, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 8, 4, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setMinimumSize(QtCore.QSize(600, 240))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 1, 0, 1, 1)
        self.return_pushButton = QtWidgets.QPushButton(self.widget_3)
        self.return_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.return_pushButton.setStyleSheet("#return_pushButton{\n"
"    border:none;\n"
"    font: 10pt \"Arial\";\n"
"}")
        self.return_pushButton.setObjectName("return_pushButton")
        self.gridLayout_4.addWidget(self.return_pushButton, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setMinimumSize(QtCore.QSize(30, 30))
        self.label_4.setStyleSheet("border-image: url(:/icons/icons/密码.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.Login_Account_lineEdit_3 = QtWidgets.QLineEdit(self.widget_3)
        self.Login_Account_lineEdit_3.setMinimumSize(QtCore.QSize(200, 30))
        self.Login_Account_lineEdit_3.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.Login_Account_lineEdit_3.setText("")
        self.Login_Account_lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Login_Account_lineEdit_3.setObjectName("Login_Account_lineEdit_3")
        self.horizontalLayout_8.addWidget(self.Login_Account_lineEdit_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setStyleSheet("border-image: url(:/icons/icons/密码.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.Login_Account_lineEdit_4 = QtWidgets.QLineEdit(self.widget_3)
        self.Login_Account_lineEdit_4.setMinimumSize(QtCore.QSize(200, 30))
        self.Login_Account_lineEdit_4.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.Login_Account_lineEdit_4.setText("")
        self.Login_Account_lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Login_Account_lineEdit_4.setObjectName("Login_Account_lineEdit_4")
        self.horizontalLayout_9.addWidget(self.Login_Account_lineEdit_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setStyleSheet("border-image: url(:/icons/icons/用户.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.logon_Account_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.logon_Account_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.logon_Account_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.logon_Account_lineEdit.setObjectName("logon_Account_lineEdit")
        self.horizontalLayout_5.addWidget(self.logon_Account_lineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.LogonpushButton = QtWidgets.QPushButton(self.widget_3)
        self.LogonpushButton.setMinimumSize(QtCore.QSize(230, 40))
        self.LogonpushButton.setStyleSheet("#LogonpushButton{\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0, 170, 255);\n"
"    border-radius:7px;\n"
"}\n"
"#LogonpushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#LogonpushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/注册.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogonpushButton.setIcon(icon2)
        self.LogonpushButton.setObjectName("LogonpushButton")
        self.gridLayout_3.addWidget(self.LogonpushButton, 6, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 3, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 2, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(28, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem17, 1, 4, 2, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_5.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(600, 200))
        self.groupBox_2.setStyleSheet("#groupBox_2{\n"
"    border-image: url(:/images/images/02.png);\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem18, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.minimize_pushButton.setStyleSheet("border:none;")
        self.minimize_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/减去.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_pushButton.setIcon(icon3)
        self.minimize_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.minimize_pushButton.setObjectName("minimize_pushButton")
        self.horizontalLayout_2.addWidget(self.minimize_pushButton)
        self.Full_screen_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.Full_screen_pushButton.setStyleSheet("border:none;")
        self.Full_screen_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/全屏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Full_screen_pushButton.setIcon(icon4)
        self.Full_screen_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.Full_screen_pushButton.setObjectName("Full_screen_pushButton")
        self.horizontalLayout_2.addWidget(self.Full_screen_pushButton)
        self.Full_screen_pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Full_screen_pushButton_2.setStyleSheet("border:none;")
        self.Full_screen_pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/小屏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Full_screen_pushButton_2.setIcon(icon5)
        self.Full_screen_pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.Full_screen_pushButton_2.setObjectName("Full_screen_pushButton_2")
        self.horizontalLayout_2.addWidget(self.Full_screen_pushButton_2)
        self.close_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.close_pushButton.setStyleSheet("border:none;")
        self.close_pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/错号.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_pushButton.setIcon(icon6)
        self.close_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_2.addWidget(self.close_pushButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem19, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem20, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.close_pushButton.clicked.connect(MainWindow.close)
        self.Full_screen_pushButton.clicked.connect(self.Full_screen_pushButton_2.show)
        self.Full_screen_pushButton.clicked.connect(MainWindow.showMaximized)
        self.Full_screen_pushButton.clicked.connect(self.Full_screen_pushButton.hide)
        self.Full_screen_pushButton_2.clicked.connect(self.Full_screen_pushButton_2.hide)
        self.Full_screen_pushButton_2.clicked.connect(self.Full_screen_pushButton.show)
        self.Full_screen_pushButton_2.clicked.connect(MainWindow.showNormal)
        self.minimize_pushButton.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.minimize_pushButton, self.Full_screen_pushButton)
        MainWindow.setTabOrder(self.Full_screen_pushButton, self.Full_screen_pushButton_2)
        MainWindow.setTabOrder(self.Full_screen_pushButton_2, self.close_pushButton)
        MainWindow.setTabOrder(self.close_pushButton, self.Login_Account_lineEdit)
        MainWindow.setTabOrder(self.Login_Account_lineEdit, self.Login_Account_lineEdit_2)
        MainWindow.setTabOrder(self.Login_Account_lineEdit_2, self.automatic_logon_checkBox)
        MainWindow.setTabOrder(self.automatic_logon_checkBox, self.remember_psw_checkBox)
        MainWindow.setTabOrder(self.remember_psw_checkBox, self.forgot_psw_pushButton)
        MainWindow.setTabOrder(self.forgot_psw_pushButton, self.LoginpushButton)
        MainWindow.setTabOrder(self.LoginpushButton, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.logon_account_pushButton)
        MainWindow.setTabOrder(self.logon_account_pushButton, self.logon_Account_lineEdit)
        MainWindow.setTabOrder(self.logon_Account_lineEdit, self.Login_Account_lineEdit_3)
        MainWindow.setTabOrder(self.Login_Account_lineEdit_3, self.Login_Account_lineEdit_4)
        MainWindow.setTabOrder(self.Login_Account_lineEdit_4, self.LogonpushButton)
        MainWindow.setTabOrder(self.LogonpushButton, self.return_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.automatic_logon_checkBox.setText(_translate("MainWindow", "自动登录"))
        self.forgot_psw_pushButton.setText(_translate("MainWindow", "忘记密码"))
        self.LoginpushButton.setText(_translate("MainWindow", "登录"))
        self.remember_psw_checkBox.setText(_translate("MainWindow", "记住密码"))
        self.Login_Account_lineEdit.setPlaceholderText(_translate("MainWindow", "账号："))
        self.logon_account_pushButton.setText(_translate("MainWindow", "注册账号"))
        self.Login_Account_lineEdit_2.setPlaceholderText(_translate("MainWindow", "密码："))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>二维码登录</p></body></html>"))
        self.pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.return_pushButton.setText(_translate("MainWindow", "返回"))
        self.Login_Account_lineEdit_3.setPlaceholderText(_translate("MainWindow", "密码："))
        self.Login_Account_lineEdit_4.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.logon_Account_lineEdit.setPlaceholderText(_translate("MainWindow", "设置账号："))
        self.LogonpushButton.setText(_translate("MainWindow", "注册"))
        self.minimize_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>最小化</p></body></html>"))
        self.minimize_pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Full_screen_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>全屏</p></body></html>"))
        self.Full_screen_pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Full_screen_pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>还原</p></body></html>"))
        self.Full_screen_pushButton_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.close_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭</p></body></html>"))
        self.close_pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
import resources_rc


class main(QtWidgets.QMainWindow):
    def __init__(self):
        super(QMainWindow, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.ui.Full_screen_pushButton_2.hide()
        self.ui.LoginpushButton.clicked.connect(self.login_d)
        self.ui.return_pushButton.clicked.connect(lambda: self.ui.stackedWidget.setCurrentIndex(0))
        self.ui.logon_account_pushButton.clicked.connect(lambda: self.ui.stackedWidget.setCurrentIndex(1))
        self.show()

    # 拖动
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton and self.isMaximized() == False:
            self.m_flag = True
            self.m_Position = event.globalPos() - self.pos()  # 获取鼠标相对窗口的位置
            event.accept()
            self.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))  # 更改鼠标图标

    def mouseMoveEvent(self, mouse_event):
        if QtCore.Qt.LeftButton and self.m_flag:
            self.move(mouse_event.globalPos() - self.m_Position)  # 更改窗口位置
            mouse_event.accept()

    def mouseReleaseEvent(self, mouse_event):
        self.m_flag = False
        self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

    def login_d(self):
        sql = "SELECT * FROM user"
        name = DataB.Db_R(sql)
        name_tmp = self.ui.Login_Account_lineEdit.text()
        passwd_tmp = self.ui.Login_Account_lineEdit_2.text()
        for i in range(len(name)):
                if name["用户名"][i] == name_tmp and name["密码"][i] == passwd_tmp:
                    self.win = Tr.main()
                    self.close()
                else:
                    pass
