# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(865, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(189, 124, 124, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.176136 rgba(25, 54, 211, 255), stop:0.323864 rgba(126, 14, 81, 255), stop:0.471591 rgba(234, 11, 11, 255), stop:0.607955 rgba(244, 70, 5, 255), stop:0.744318 rgba(255, 136, 0, 255), stop:0.892045 rgba(239, 236, 55, 255));\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 415, 521))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Algerian\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2.addWidget(self.widget1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.widget2 = QtWidgets.QWidget(self.frame_4)
        self.widget2.setGeometry(QtCore.QRect(-8, 0, 461, 34))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(270, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.min_button = QtWidgets.QPushButton(self.widget2)
        self.min_button.setMinimumSize(QtCore.QSize(50, 30))
        self.min_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#min_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.min_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res1/icons/缩小.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_button.setIcon(icon)
        self.min_button.setObjectName("min_button")
        self.horizontalLayout_2.addWidget(self.min_button)
        self.max_button = QtWidgets.QPushButton(self.widget2)
        self.max_button.setMinimumSize(QtCore.QSize(50, 30))
        self.max_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#max_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.max_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res1/icons/全屏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_button.setIcon(icon1)
        self.max_button.setObjectName("max_button")
        self.horizontalLayout_2.addWidget(self.max_button)
        self.close_button = QtWidgets.QPushButton(self.widget2)
        self.close_button.setMinimumSize(QtCore.QSize(50, 30))
        self.close_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#close_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res1/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget_2 = QtWidgets.QWidget(self.frame_6)
        self.widget_2.setGeometry(QtCore.QRect(40, 20, 419, 431))
        self.widget_2.setObjectName("widget_2")
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.username_lineEdit.setGeometry(QtCore.QRect(30, 130, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.password_lineEdit.setGeometry(QtCore.QRect(30, 200, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.login_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.login_pushButton.setGeometry(QtCore.QRect(160, 290, 141, 41))
        self.login_pushButton.setStyleSheet("\n"
"#login_pushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#login_pushButton:hover{\n"
"\n"
"    background-color: rgb(196, 196, 196);\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#login_pushButton:press{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res1/icons/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_pushButton.setIcon(icon3)
        self.login_pushButton.setObjectName("login_pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(30, 260, 79, 20))
        self.checkBox.setObjectName("checkBox")
        self.register_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.register_pushButton.setGeometry(QtCore.QRect(30, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setStyleSheet("\n"
"#register_pushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#register_pushButton:hover{\n"
"    background-color:rgb(196, 196, 196);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#register_pushButton:press{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res1/icons/注册邀请.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_pushButton.setIcon(icon4)
        self.register_pushButton.setObjectName("register_pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(100, 0, 121, 121))
        self.label_3.setStyleSheet("image: url(:/icons/res1/icons/app-icon.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(30, 350, 91, 16))
        self.label_4.setStyleSheet("color: rgb(127,127,149);")
        self.label_4.setObjectName("label_4")
        self.widget3 = QtWidgets.QWidget(self.widget_2)
        self.widget3.setGeometry(QtCore.QRect(30, 380, 271, 41))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.qq_login = QtWidgets.QPushButton(self.widget3)
        self.qq_login.setMinimumSize(QtCore.QSize(40, 30))
        self.qq_login.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qq_login.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"#qq_login:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    \n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}")
        self.qq_login.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res1/icons/QQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qq_login.setIcon(icon5)
        self.qq_login.setIconSize(QtCore.QSize(30, 30))
        self.qq_login.setObjectName("qq_login")
        self.horizontalLayout_5.addWidget(self.qq_login)
        self.wechat_login = QtWidgets.QPushButton(self.widget3)
        self.wechat_login.setMinimumSize(QtCore.QSize(50, 30))
        self.wechat_login.setMaximumSize(QtCore.QSize(50, 16777215))
        self.wechat_login.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"#wechat_login:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.wechat_login.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res1/icons/微信 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wechat_login.setIcon(icon6)
        self.wechat_login.setIconSize(QtCore.QSize(30, 30))
        self.wechat_login.setObjectName("wechat_login")
        self.horizontalLayout_5.addWidget(self.wechat_login)
        self.weibo_login = QtWidgets.QPushButton(self.widget3)
        self.weibo_login.setMinimumSize(QtCore.QSize(50, 30))
        self.weibo_login.setMaximumSize(QtCore.QSize(50, 16777215))
        self.weibo_login.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#weibo_login:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.weibo_login.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res1/icons/微博.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weibo_login.setIcon(icon7)
        self.weibo_login.setIconSize(QtCore.QSize(30, 30))
        self.weibo_login.setObjectName("weibo_login")
        self.horizontalLayout_5.addWidget(self.weibo_login)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "    欢迎来到亿途  "))
        self.label_2.setText(_translate("Form", "  Welcome To\n"
"Trip Memory !"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "账号："))
        self.password_lineEdit.setPlaceholderText(_translate("Form", "密码："))
        self.login_pushButton.setText(_translate("Form", "登录"))
        self.checkBox.setText(_translate("Form", "记住"))
        self.register_pushButton.setText(_translate("Form", "注册"))
        self.label_4.setText(_translate("Form", "其他登录方式："))
import res2_rc
