# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'achievement_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import res1_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(918, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-radius:30px;\n"
"    background-color: rgb(0, 255, 127);\n"
"    \n"
"    background-color: rgb(170, 0, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("\n"
"#frame_4{\n"
"    border-radius:30px;\n"
"    background-color: rgb(255, 111, 101);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_17.setContentsMargins(15, 12, 15, 12)
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("border-radius:30px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_16.setSpacing(9)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(50, 50))
        self.widget_2.setStyleSheet("image: url(:/icons/res1/icons/option.png);\n"
"border:none")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("font: 12pt \"宋体\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("image: url(:/icons/res1/icons/research.png);")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.borrow_user_search_lineEdit = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borrow_user_search_lineEdit.sizePolicy().hasHeightForWidth())
        self.borrow_user_search_lineEdit.setSizePolicy(sizePolicy)
        self.borrow_user_search_lineEdit.setStyleSheet("font: 12pt \"宋体\";")
        self.borrow_user_search_lineEdit.setObjectName("borrow_user_search_lineEdit")
        self.horizontalLayout.addWidget(self.borrow_user_search_lineEdit)
        self.search_borrow_user_pushButton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_borrow_user_pushButton.sizePolicy().hasHeightForWidth())
        self.search_borrow_user_pushButton.setSizePolicy(sizePolicy)
        self.search_borrow_user_pushButton.setStyleSheet("\n"
"#search_borrow_user_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#search_borrow_user_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"#search_borrow_user_pushButton{\n"
"    \n"
"    border-radius:30px;\n"
"\n"
"}")
        self.search_borrow_user_pushButton.setObjectName("search_borrow_user_pushButton")
        self.horizontalLayout.addWidget(self.search_borrow_user_pushButton)
        self.horizontalLayout_15.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refresh_pushButton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_pushButton.sizePolicy().hasHeightForWidth())
        self.refresh_pushButton.setSizePolicy(sizePolicy)
        self.refresh_pushButton.setStyleSheet("#refresh_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#refresh_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res1/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_pushButton.setIcon(icon)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.horizontalLayout_3.addWidget(self.refresh_pushButton)
        self.add_achieve_pushButton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_achieve_pushButton.sizePolicy().hasHeightForWidth())
        self.add_achieve_pushButton.setSizePolicy(sizePolicy)
        self.add_achieve_pushButton.setStyleSheet("#add_achieve_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#add_achieve_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res1/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_achieve_pushButton.setIcon(icon1)
        self.add_achieve_pushButton.setObjectName("add_achieve_pushButton")
        self.horizontalLayout_3.addWidget(self.add_achieve_pushButton)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17.addWidget(self.frame_6)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("border-radius:30px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setStyleSheet("font: 12pt \"宋体\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_4.raise_()
        self.widget.raise_()
        self.comboBox.raise_()
        self.widget_2.raise_()
        self.borrow_user_search_lineEdit.raise_()
        self.search_borrow_user_pushButton.raise_()
        self.refresh_pushButton.raise_()
        self.add_achieve_pushButton.raise_()
        self.frame_5.raise_()
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("\n"
"#frame_3{\n"
"    border-radius:30px;\n"
"\n"
"background-color: rgb(0, 172, 83);\n"
"    background-color: rgb(24, 255, 97);\n"
"    background-color: rgb(49, 203, 93);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("border-radius:30px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bar_widget = QtWidgets.QWidget(self.frame_7)
        self.bar_widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bar_widget.setObjectName("bar_widget")
        self.horizontalLayout_18.addWidget(self.bar_widget)
        self.horizontalLayout_20.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("border-radius:30px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.bar_widget_2 = QtWidgets.QWidget(self.frame_8)
        self.bar_widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bar_widget_2.setObjectName("bar_widget_2")
        self.horizontalLayout_19.addWidget(self.bar_widget_2)
        self.horizontalLayout_20.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "用户ID"))
        self.comboBox.setItemText(1, _translate("Form", "成就名称"))
        self.comboBox.setItemText(2, _translate("Form", "成就类型"))
        self.comboBox.setItemText(3, _translate("Form", "成就级别"))
        self.comboBox.setItemText(4, _translate("Form", "颁奖机构"))
        self.comboBox.setItemText(5, _translate("Form", "获得时间"))
        self.comboBox.setItemText(6, _translate("Form", "描述说明"))
        self.borrow_user_search_lineEdit.setPlaceholderText(_translate("Form", "请搜索"))
        self.search_borrow_user_pushButton.setText(_translate("Form", "搜索"))
        self.refresh_pushButton.setText(_translate("Form", "刷新"))
        self.add_achieve_pushButton.setText(_translate("Form", "添加成就"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "用户ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "成就名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "成就类型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "成就级别"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "颁奖机构"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "获得时间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "描述说明"))
