# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import res1_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(835, 777)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("\n"
"#frame_2{\n"
"    border-radius:30px;\n"
"\n"
"\n"
"    background-color: rgb(255, 111, 101);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_11.setSpacing(15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.clock_widget = QtWidgets.QWidget(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.clock_widget.sizePolicy().hasHeightForWidth())
        self.clock_widget.setSizePolicy(sizePolicy)
        self.clock_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px")
        self.clock_widget.setObjectName("clock_widget")
        self.verticalLayout_12.addWidget(self.clock_widget)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("border-radius:30px")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(53, 255, 188);\n"
"background-color: rgb(211, 211, 211);\n"
"background-color: rgb(255, 209, 102);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(25, 0))
        self.label.setStyleSheet("image: url(:/icons/res1/icons/announce.png);\n"
"font: 15pt \"Agency FB\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.totol_annouce_label = QtWidgets.QLabel(self.frame_5)
        self.totol_annouce_label.setObjectName("totol_annouce_label")
        self.horizontalLayout_4.addWidget(self.totol_annouce_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.refresh_pushButton.setStyleSheet("#refresh_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#refresh_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res1/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_pushButton.setIcon(icon)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.horizontalLayout_2.addWidget(self.refresh_pushButton)
        self.add_annou_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.add_annou_pushButton.setStyleSheet("#add_annou_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#add_annou_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res1/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_annou_pushButton.setIcon(icon1)
        self.add_annou_pushButton.setObjectName("add_annou_pushButton")
        self.horizontalLayout_2.addWidget(self.add_annou_pushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.annou_info_tableWidget = QtWidgets.QTableWidget(self.frame_7)
        self.annou_info_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.annou_info_tableWidget.setObjectName("annou_info_tableWidget")
        self.annou_info_tableWidget.setColumnCount(3)
        self.annou_info_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.annou_info_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.annou_info_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.annou_info_tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.annou_info_tableWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:30px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("image: url(:/icons/res1/icons/announce.png);\n"
"image: url(:/icons/res1/icons/goal.png);\n"
"font: 15pt \"Agency FB\";")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.totol_goal_label = QtWidgets.QLabel(self.frame_8)
        self.totol_goal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Microsoft YaHei UI\";")
        self.totol_goal_label.setObjectName("totol_goal_label")
        self.horizontalLayout_7.addWidget(self.totol_goal_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.refresh_goal_pushButton = QtWidgets.QPushButton(self.frame_8)
        self.refresh_goal_pushButton.setStyleSheet("#refresh_goal_pushButton{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#refresh_goal_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#refresh_goal_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res1/icons/refresh2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_goal_pushButton.setIcon(icon2)
        self.refresh_goal_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.refresh_goal_pushButton.setObjectName("refresh_goal_pushButton")
        self.horizontalLayout_9.addWidget(self.refresh_goal_pushButton)
        self.add_goal_pushButton = QtWidgets.QPushButton(self.frame_8)
        self.add_goal_pushButton.setStyleSheet("#add_goal_pushButton{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#add_goal_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#add_goal_pushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res1/icons/add2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_goal_pushButton.setIcon(icon3)
        self.add_goal_pushButton.setIconSize(QtCore.QSize(25, 25))
        self.add_goal_pushButton.setObjectName("add_goal_pushButton")
        self.horizontalLayout_9.addWidget(self.add_goal_pushButton)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setStyleSheet("\n"
"border-radius:30px;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9.addWidget(self.frame_10)
        self.book_recommend_tableWidget = QtWidgets.QTableWidget(self.frame_9)
        self.book_recommend_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"")
        self.book_recommend_tableWidget.setObjectName("book_recommend_tableWidget")
        self.book_recommend_tableWidget.setColumnCount(5)
        self.book_recommend_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.book_recommend_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.book_recommend_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.book_recommend_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.book_recommend_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.book_recommend_tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_9.addWidget(self.book_recommend_tableWidget)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "公告栏"))
        self.totol_annouce_label.setText(_translate("Form", "TextLabel"))
        self.refresh_pushButton.setText(_translate("Form", "刷新"))
        self.add_annou_pushButton.setText(_translate("Form", "发布公告"))
        item = self.annou_info_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "公告标题"))
        item = self.annou_info_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "公共内容"))
        item = self.annou_info_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "发布时间"))
        self.label_5.setText(_translate("Form", "目标记录"))
        self.totol_goal_label.setText(_translate("Form", "TextLabel"))
        self.refresh_goal_pushButton.setText(_translate("Form", "刷新"))
        self.add_goal_pushButton.setText(_translate("Form", "添加目标"))
        item = self.book_recommend_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "名称"))
        item = self.book_recommend_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "计划"))
        item = self.book_recommend_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "进度"))
        item = self.book_recommend_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "开始时间"))
        item = self.book_recommend_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "截止时间"))

