# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import res1_rc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(854, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.397727 rgba(122, 107, 174, 255), stop:0.539773 rgba(216, 26, 199, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.875 rgba(239, 117, 64, 255));\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 415, 521))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Algerian\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(-8, 0, 461, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(270, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.min_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.min_button.setMinimumSize(QtCore.QSize(50, 30))
        self.min_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#min_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#min_button:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"")
        self.min_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res1/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_button.setIcon(icon)
        self.min_button.setObjectName("min_button")
        self.horizontalLayout_2.addWidget(self.min_button)
        self.max_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.max_button.setMinimumSize(QtCore.QSize(50, 30))
        self.max_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#max_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#max_button:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"")
        self.max_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res1/icons/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_button.setIcon(icon1)
        self.max_button.setObjectName("max_button")
        self.horizontalLayout_2.addWidget(self.max_button)
        self.close_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.close_button.setMinimumSize(QtCore.QSize(50, 30))
        self.close_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding-bottom:5px;\n"
"}\n"
"#close_button:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#close_button:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"")
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res1/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget_2 = QtWidgets.QWidget(self.frame_6)
        self.widget_2.setGeometry(QtCore.QRect(40, 20, 419, 431))
        self.widget_2.setObjectName("widget_2")
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.username_lineEdit.setGeometry(QtCore.QRect(30, 130, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.password_lineEdit.setGeometry(QtCore.QRect(30, 200, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.return_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.return_pushButton.setGeometry(QtCore.QRect(30, 340, 141, 41))
        self.return_pushButton.setStyleSheet("\n"
"#return_pushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#return_pushButton:hover{\n"
"    background-color: rgb(196, 196, 196);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#return_pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res1/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_pushButton.setIcon(icon3)
        self.return_pushButton.setObjectName("return_pushButton")
        self.register_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.register_pushButton.setGeometry(QtCore.QRect(170, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setStyleSheet("\n"
"#register_pushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#register_pushButton:hover{\n"
"    background-color:rgb(196, 196, 196);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#register_pushButton:press{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"#register_pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res1/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_pushButton.setIcon(icon4)
        self.register_pushButton.setObjectName("register_pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(100, 0, 121, 121))
        self.label_3.setStyleSheet("image: url(:/icons/res1/icons/yitu.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.confirm_password_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.confirm_password_lineEdit.setGeometry(QtCore.QRect(30, 270, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.confirm_password_lineEdit.setFont(font)
        self.confirm_password_lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.confirm_password_lineEdit.setText("")
        self.confirm_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password_lineEdit.setObjectName("confirm_password_lineEdit")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.min_button.clicked.connect(Form.showNormal) # type: ignore
        self.max_button.clicked.connect(Form.showFullScreen) # type: ignore
        self.close_button.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "    欢迎来到亿途  "))
        self.label_2.setText(_translate("Form", "  Welcome To\n"
"Trip Memory !"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "账号："))
        self.password_lineEdit.setPlaceholderText(_translate("Form", "密码："))
        self.return_pushButton.setText(_translate("Form", "返回"))
        self.register_pushButton.setText(_translate("Form", "注册"))
        self.confirm_password_lineEdit.setPlaceholderText(_translate("Form", "确认密码："))
